version: "3"
services:
 web:
  container_name: visor
  restart: always
  build: .
  ports:
   - "4000:4000"
  links:
   - mongo
 mongo:
  container_name: mymongodatabase
  image: mongo
  ports:
   - "4001:27017"